pupServer:
  url: http://localhost
  db:
    path: C:\vPinball\PinUPSystem\PUPDatabase.db
    filter: ifnull(GameTheme, 1) <> 'Adult'

httpServer:
  port: 8080
  logFormat: dev
  logLevel: error

options:
  defaultView: playlists  # home | playlists
  filters:
    category: true
    theme: true
    type: true
    decade: true
    emulator: true
    manufacturer: true
    favorites: true
  game:
    info: true
    help: true
    playfield: true
    highscore: true
    media:
      topper: false
      backglass: false
      dmd: false
      playfield: true
      help: false
      info: false

media:
  useThumbs: true
  cacheInMinutes: 20
  playfieldRotation: true
  folders:
    topper: Topper
    backglass: BackGlass
    dmd: Menu
    playfield: Playfield
    help: GameHelp
    info: GameInfo
    highscore: Other2
